import {
  type AppKitNetwork,
  arbitrum,
  aurora,
  avalanche,
  base,
  berachain,
  bevmMainnet,
  bitcoin,
  bitgert,
  bitlayer,
  blast,
  bob,
  bounceBit,
  bsc,
  celo,
  coreDao,
  cronos,
  defineChain,
  fantom,
  gnosis,
  gravity,
  hychain,
  kava,
  linea,
  lumiaMainnet,
  mainnet,
  manta,
  mantle,
  merlin,
  metis,
  mode,
  moonbeam,
  moonriver,
  morph,
  okc,
  opBNB,
  optimism,
  polygon,
  pulsechain,
  rootstock,
  scroll,
  sepolia,
  solana,
  sonic,
  taiko,
  telos,
  theta,
  tron,
  wanchain,
  worldchain,
  zetachain,
  zkLinkNova,
  zksync,
} from '@reown/appkit/networks';

const b2Network = defineChain({
  id: 223,
  name: 'B2 Mainnet',
  nativeCurrency: {
    decimals: 18,
    name: 'Bitcoin',
    symbol: 'BTC',
  },
  rpcUrls: {
    default: {
      http: ['https://rpc.bsquared.network'],
    },
  },
  blockExplorers: {
    default: {
      name: 'B2 Explorer',
      url: 'https://explorer.bsquared.network',
    },
  },
  contracts: {
    multicall3: {
      address: '0xca11bde05977b3631167028862be2a173976ca11',
      blockCreated: 1632781,
    },
  },
  chainNamespace: 'eip155',
  caipNetworkId: 'eip155:223',
  testnet: false,
});
const hyperchainEVM = defineChain({
  id: 999,
  name: 'HyperEVM',
  nativeCurrency: {
    decimals: 18,
    name: 'Hyperchain',
    symbol: 'HYPE',
  },
  rpcUrls: {
    default: {
      http: ['https://rpc.hyperliquid.xyz/evm'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Hyperchain Explorer',
      url: 'https://purrsec.com',
    },
  },
  contracts: {
    multicall3: {
      address: '0xca11bde05977b3631167028862be2a173976ca11',
      blockCreated: 1632781,
    },
  },
  chainNamespace: 'eip155',
  caipNetworkId: 'eip155:999',
  testnet: false,
});

// Configure networks
// Create custom networks: https://docs.reown.com/cloud/chains/chain-list
export const networks: [AppKitNetwork, ...AppKitNetwork[]] = [
  arbitrum,
  aurora,
  avalanche,
  base,
  berachain,
  bevmMainnet,
  bitgert,
  blast,
  bob,
  bsc,
  celo,
  cronos,
  fantom,
  gnosis,
  kava,
  linea,
  mainnet,
  manta,
  mantle,
  merlin,
  metis,
  mode,
  moonbeam,
  moonriver,
  okc,
  opBNB,
  optimism,
  polygon,
  rootstock,
  scroll,
  taiko,
  tron,
  wanchain,
  worldchain,
  zkLinkNova,
  zksync,
  telos,
  coreDao,
  bitlayer,
  zetachain,
  theta,
  gravity,
  bounceBit,
  morph,
  hychain,
  pulsechain,
  sepolia,
  sonic,
  b2Network,
  hyperchainEVM,
  lumiaMainnet,
  solana,
  bitcoin,
] as [AppKitNetwork, ...AppKitNetwork[]];
